# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

csv_read_cpp <- function(filename) {
    .Call('_laf2_csv_read_cpp', PACKAGE = 'laf2', filename)
}

csv_nrow_cpp <- function(filename) {
    .Call('_laf2_csv_nrow_cpp', PACKAGE = 'laf2', filename)
}

test_dynamicarray <- function(size) {
    .Call('_laf2_test_dynamicarray', PACKAGE = 'laf2', size)
}

test_dynamicarray2r <- function(size) {
    .Call('_laf2_test_dynamicarray2r', PACKAGE = 'laf2', size)
}

test_purer <- function(size) {
    .Call('_laf2_test_purer', PACKAGE = 'laf2', size)
}

test_purer2 <- function(size) {
    .Call('_laf2_test_purer2', PACKAGE = 'laf2', size)
}

