// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// csv_read_cpp
List csv_read_cpp(std::string filename);
RcppExport SEXP _laf2_csv_read_cpp(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(csv_read_cpp(filename));
    return rcpp_result_gen;
END_RCPP
}
// csv_nrow_cpp
double csv_nrow_cpp(std::string filename);
RcppExport SEXP _laf2_csv_nrow_cpp(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(csv_nrow_cpp(filename));
    return rcpp_result_gen;
END_RCPP
}
// test_dynamicarray
int test_dynamicarray(int size);
RcppExport SEXP _laf2_test_dynamicarray(SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(test_dynamicarray(size));
    return rcpp_result_gen;
END_RCPP
}
// test_dynamicarray2r
NumericVector test_dynamicarray2r(int size);
RcppExport SEXP _laf2_test_dynamicarray2r(SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(test_dynamicarray2r(size));
    return rcpp_result_gen;
END_RCPP
}
// test_purer
SEXP test_purer(int size);
RcppExport SEXP _laf2_test_purer(SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(test_purer(size));
    return rcpp_result_gen;
END_RCPP
}
// test_purer2
SEXP test_purer2(int size);
RcppExport SEXP _laf2_test_purer2(SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(test_purer2(size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_laf2_csv_read_cpp", (DL_FUNC) &_laf2_csv_read_cpp, 1},
    {"_laf2_csv_nrow_cpp", (DL_FUNC) &_laf2_csv_nrow_cpp, 1},
    {"_laf2_test_dynamicarray", (DL_FUNC) &_laf2_test_dynamicarray, 1},
    {"_laf2_test_dynamicarray2r", (DL_FUNC) &_laf2_test_dynamicarray2r, 1},
    {"_laf2_test_purer", (DL_FUNC) &_laf2_test_purer, 1},
    {"_laf2_test_purer2", (DL_FUNC) &_laf2_test_purer2, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_laf2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
