
test5: test5.cpp buffer3.h
	g++ -o test5 -pthread -O3 test5.cpp

test4: test4.cpp
	g++ -o test4 -pthread -O3 test4.cpp

test2: test2.cpp
	g++ -o test2 -pthread -O3 test2.cpp

test3: test3.cpp
	g++ -o test3 -pthread -O3 test3.cpp
